name: CI/CD Workflow for Bible Immersive App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Use Node.js LTS (16 or 18)

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install
          npm install tailwindcss postcss autoprefixer --save-dev
          ls ./node_modules/.bin # List binaries to verify installation

      # Step 4: Verify and Initialize Tailwind CSS Config
      - name: Verify Tailwind Installation
        run: |
          if [ ! -f ./node_modules/.bin/tailwindcss ]; then
            echo "Tailwind CSS binary not found! Installation failed."
            exit 1
          fi
          ./node_modules/.bin/tailwindcss init
          echo "tailwind.config.js initialized successfully."

      # Step 5: Test Development Server Setup
      - name: Run Dev Server (Test)
        run: |
          npm run dev -- --host=127.0.0.1 --port=5173 &
          sleep 5
          curl --fail http://127.0.0.1:5173 || exit 1
        env:
          NODE_ENV: development

      # Step 6: Build Project
      - name: Build Project
        run: npm run build

      # Step 7: Deploy to Vercel
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: npx vercel --prod